apiVersion: apps/v1
kind: Deployment
metadata:
  name: reap
  labels:
    app: reap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reap
  template:
    metadata:
      labels:
        app: reap
    spec:
      containers:
      - name: reap
        image: dukeman/reap:v1.2.1
        resources: {}
        env:
        - name: DB
          value: "http://influxdb:8086"
        - name: BROKER
          value: "tcp://mqtt.leetserve.com:1883"
---
kind: Endpoints
apiVersion: v1
metadata:
  name: influxdb
subsets:
  - addresses:
      - ip: 192.168.86.30
    ports:
      - port: 8086
        name: influxdb
---
kind: Service
apiVersion: v1
metadata:
  name: influxdb
spec:
  ports:
  - port: 8086
    targetPort: 8086
    name: influxdb
