apiVersion: apps/v1
kind: Deployment
metadata:
  name: reap
  labels:
    app: reap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reap
  template:
    metadata:
      labels:
        app: reap
    spec:
      containers:
      - name: reap
        image: dukeman/reap:v1.2.8
        resources: {}
        env:
        - name: DB
          value: "http://influxdb-influxdb2.influxdb"
        - name: BROKER
          value: "tcp://mqtt.leetserve.com:1883"
        - name: BUCKET
          value: "home"
        - valueFrom:
            secretKeyRef:
              name: reap-creds
              key: INFLUXDB_TOKEN
          name: INFLUXDB_TOKEN
