apiVersion: apps/v1
kind: Deployment
metadata:
  name: reap
  labels:
    app: reap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reap
  template:
    metadata:
      labels:
        app: reap
    spec:
      containers:
      - name: reap
        image: dukeman/reap:v1.2.1
        resources: {}
        env:
        - name: DB
          value: "http://influxdb-influxdb2.influxdb.svc:8086"
        - name: BROKER
          value: "tcp://mqtt.leetserve.com:1883"
